name: Check Merge Condition

on:
  pull_request:
    branches:
      - main

jobs:
  check-test-branch-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get the current branch name
        id: branch-name
        run: echo "::set-output name=branch::$(git rev-parse --abbrev-ref HEAD)"

      - name: Check if current branch was merged into 'test'
        run: |
          CURRENT_BRANCH="${{ steps.branch-name.outputs.branch }}"
          if [[ "$(git branch --contains origin/$CURRENT_BRANCH --remote | grep 'origin/test')" != "" ]]; then
            echo "$CURRENT_BRANCH 브랜치는 test 브랜치에 머지된 적이 있습니다."
          else
            echo "Error: $CURRENT_BRANCH 브랜치는 test 브랜치에 머지된 적이 없습니다."
            exit 1
          fi
