name: Check PR Merge

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  check_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check if 'test' branch has 'dev' branch's changes
        run: |
          git fetch origin dev:dev
          CHANGES=$(git log dev..test)
          if [ -n "$CHANGES" ]; then
            echo "Changes from 'dev' branch have been merged into 'test' branch."
          else
            echo "No changes from 'dev' branch have been merged into 'test' branch."
            exit 1
          fi

